"""add transaction description and nullable account_id

Revision ID: 748ee2d39146
Revises: 841974b6702c
Create Date: 2026-03-15 19:17:17.719128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748ee2d39146'
down_revision: Union[str, None] = '841974b6702c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.String(length=500), nullable=True))
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###
