"""add health_logs

Revision ID: 8369a49f57b7
Revises: 748ee2d39146
Create Date: 2026-03-25 02:42:12.316854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8369a49f57b7'
down_revision: Union[str, None] = '748ee2d39146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_logs',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('energy_rating', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('garmin_body_battery_low', sa.Integer(), nullable=True),
    sa.Column('garmin_body_battery_high', sa.Integer(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intensity_minutes_moderate', sa.Integer(), nullable=True),
    sa.Column('intensity_minutes_vigorous', sa.Integer(), nullable=True),
    sa.Column('stress_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_logs')
    # ### end Alembic commands ###
